# Generated by Django 4.1.7 on 2023-03-29 06:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vehicle',
            old_name='vehicle_user',
            new_name='vehicle_users',
        ),
    ]
