# Generated by Django 4.1.7 on 2023-03-29 06:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_rename_vehicle_user_vehicle_vehicle_users'),
    ]

    operations = [
        migrations.RenameField(
            model_name='users',
            old_name='user_id',
            new_name='users_id',
        ),
        migrations.RenameField(
            model_name='users',
            old_name='user_level',
            new_name='users_level',
        ),
        migrations.RenameField(
            model_name='users',
            old_name='user_name',
            new_name='users_name',
        ),
        migrations.RenameField(
            model_name='users',
            old_name='user_phone',
            new_name='users_phone',
        ),
    ]
