# Generated by Django 4.1.7 on 2023-03-29 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_rename_user_id_users_users_id_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='users',
            old_name='users_level',
            new_name='level',
        ),
        migrations.RenameField(
            model_name='users',
            old_name='users_phone',
            new_name='phone',
        ),
        migrations.RenameField(
            model_name='vehicle',
            old_name='vehicle_addres',
            new_name='addres',
        ),
        migrations.RenameField(
            model_name='vehicle',
            old_name='vehicle_age',
            new_name='age',
        ),
        migrations.RemoveField(
            model_name='users',
            name='users_id',
        ),
        migrations.RemoveField(
            model_name='vehicle',
            name='vehicle_id',
        ),
        migrations.AlterField(
            model_name='users',
            name='id',
            field=models.CharField(max_length=15, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='id',
            field=models.CharField(max_length=15, primary_key=True, serialize=False),
        ),
    ]
