# Generated by Django 4.1.7 on 2023-03-31 05:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_rename_users_name_users_name_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='users',
            old_name='name',
            new_name='users_name',
        ),
        migrations.RenameField(
            model_name='vehicle',
            old_name='name',
            new_name='vehicle_name',
        ),
    ]
