# Generated by Django 4.1.7 on 2023-04-19 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_rename_name_users_users_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BasicData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('basicData_name', models.CharField(max_length=20)),
                ('addres', models.CharField(max_length=100)),
                ('age', models.IntegerField(blank=True)),
                ('gender', models.CharField(choices=[('F', 'Female'), ('M', 'Male')], max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doctor_name', models.CharField(max_length=20)),
                ('gender', models.CharField(choices=[('F', 'Female'), ('M', 'Male')], max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='HealthyData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('healthydata_name', models.DateField(auto_now_add=True)),
                ('blood_oxygen', models.IntegerField(blank=True)),
                ('heartbeat', models.IntegerField(blank=True)),
                ('longitude', models.DecimalField(decimal_places=2, max_digits=12)),
                ('latitude', models.DecimalField(decimal_places=2, max_digits=12)),
            ],
        ),
        migrations.RenameField(
            model_name='vehicle',
            old_name='vehicle_users',
            new_name='vehicle',
        ),
        migrations.RemoveField(
            model_name='vehicle',
            name='addres',
        ),
        migrations.RemoveField(
            model_name='vehicle',
            name='age',
        ),
        migrations.AlterField(
            model_name='users',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='users',
            name='level',
            field=models.CharField(choices=[('ordinary', 'Ordinary'), ('medical', 'Medical')], max_length=20),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
