# Generated by Django 4.1.7 on 2023-04-26 04:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_account_delete_aaa'),
    ]

    operations = [
        migrations.RenameField(
            model_name='account',
            old_name='account_users',
            new_name='users_account',
        ),
    ]
