# Generated by Django 4.1.7 on 2023-04-26 04:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_rename_account_users_account_users_account'),
    ]

    operations = [
        migrations.RenameField(
            model_name='account',
            old_name='users_account',
            new_name='account',
        ),
    ]
