# Generated by Django 4.1.7 on 2023-05-10 04:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_rename_users_account_account_account'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='account',
        ),
        migrations.RemoveField(
            model_name='vehicle',
            name='vehicle',
        ),
    ]
