# Generated by Django 4.1.7 on 2023-05-10 04:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_remove_account_account_remove_vehicle_vehicle'),
    ]

    operations = [
        migrations.RenameField(
            model_name='users',
            old_name='users_name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='vehicle',
            old_name='vehicle_name',
            new_name='name',
        ),
    ]
